/**
 * Builds the Rust fixture the Soroban tests use: real signatures produced by
 * this TypeScript co-signer and agent, over payloads computed from real
 * authorization entries. The Soroban tests then check them with OpenZeppelin's
 * own `do_check_auth`, so the two halves cannot silently disagree.
 */
import { Buffer } from "buffer";
import { ProvenanceCosigner } from "./cosigner.js";
import { buildAuthDigest, signaturePayloadOf } from "./auth.js";
import { ACCOUNT, CATALOG, KEYS, NOW, PASSPHRASE, PLANS, RULE_ID, SOUTHGATE, NORTHWIND, TOKEN, TRANSCRIPT, VERIFIER, entryFor, request } from "./scenario.js";

export function cosignerFor() {
  return new ProvenanceCosigner({
    secret: KEYS.cosigner.secret(),
    account: ACCOUNT,
    token: TOKEN,
    ruleId: RULE_ID,
    networkPassphrase: PASSPHRASE,
    verifier: VERIFIER,
    deviceKeys: [KEYS.device.publicKey()],
    catalog: CATALOG,
    now: () => NOW,
  });
}

const hex = (b: Buffer | Uint8Array) => Buffer.from(b).toString("hex");

export function buildFixture() {
  const cosigner = cosignerFor();

  // Clean: "buy the cheapest ledger report" -> Southgate, 0.008 USDC.
  const clean = entryFor(SOUTHGATE, 80_000n);
  const d1 = cosigner.review({
    request: request({ product: "ledger-report", maxAmount: "100000" }),
    plan: PLANS.clean,
    transcript: TRANSCRIPT,
    payIndex: 0,
    authEntry: clean.toXDR("base64"),
  });
  if (d1.verdict !== "cosign") throw new Error(`expected cosign, got ${JSON.stringify(d1)}`);
  const cleanPayload = signaturePayloadOf(clean, PASSPHRASE);
  const cleanDigest = buildAuthDigest(cleanPayload, [RULE_ID]);

  // Steered: the injected note picks the full dataset at Northwind, 0.025 USDC (allowlisted, within caps).
  const steered = entryFor(NORTHWIND, 250_000n, { nonce: 43n });
  const d2 = cosigner.review({
    request: request({ product: "ledger-report", maxAmount: "300000" }, { nonce: "req-2" }),
    plan: PLANS.steered,
    transcript: TRANSCRIPT,
    payIndex: 0,
    authEntry: steered.toXDR("base64"),
  });
  if (d2.verdict !== "escalate") throw new Error(`expected escalate, got ${d2.verdict}`);
  const steeredPayload = signaturePayloadOf(steered, PASSPHRASE);
  const steeredDigest = buildAuthDigest(steeredPayload, [RULE_ID]);

  return {
    ruleId: RULE_ID,
    token: TOKEN,
    southgate: SOUTHGATE,
    northwind: NORTHWIND,
    agentPk: hex(KEYS.agent.rawPublicKey()),
    cosignerPk: hex(KEYS.cosigner.rawPublicKey()),
    cleanPayload: hex(cleanPayload),
    cleanAmount: "80000",
    cleanAgentSig: hex(KEYS.agent.sign(cleanDigest)),
    cleanCosignerSig: hex(d1.signature.signature),
    steeredPayload: hex(steeredPayload),
    steeredAmount: "250000",
    steeredAgentSig: hex(KEYS.agent.sign(steeredDigest)),
    steeredWhy: d2.why.join("; "),
  };
}

export function fixtureRust(): string {
  const f = buildFixture();
  const lines = [
    "// Generated by research/prototype/scripts/gen-fixture.ts. Do not edit.",
    "// Signatures made by the TypeScript agent and provenance co-signer.",
    `pub const RULE_ID: u32 = ${f.ruleId};`,
    `pub const TOKEN: &str = "${f.token}";`,
    `pub const SOUTHGATE: &str = "${f.southgate}";`,
    `pub const NORTHWIND: &str = "${f.northwind}";`,
    `pub const AGENT_PK: &str = "${f.agentPk}";`,
    `pub const COSIGNER_PK: &str = "${f.cosignerPk}";`,
    `pub const CLEAN_PAYLOAD: &str = "${f.cleanPayload}";`,
    `pub const CLEAN_AMOUNT: i128 = ${f.cleanAmount};`,
    `pub const CLEAN_AGENT_SIG: &str = "${f.cleanAgentSig}";`,
    `pub const CLEAN_COSIGNER_SIG: &str = "${f.cleanCosignerSig}";`,
    `pub const STEERED_PAYLOAD: &str = "${f.steeredPayload}";`,
    `pub const STEERED_AMOUNT: i128 = ${f.steeredAmount};`,
    `pub const STEERED_AGENT_SIG: &str = "${f.steeredAgentSig}";`,
    `// Co-signer verdict for the steered payment: escalate (${f.steeredWhy}).`,
    "",
  ];
  return lines.join("\n");
}
