// Generated by research/prototype/scripts/gen-fixture.ts. Do not edit.
// Signatures made by the TypeScript agent and provenance co-signer.
pub const RULE_ID: u32 = 0;
pub const TOKEN: &str = "CBIELTK6YBZJU5UP2WWQEUCYKLPU6AUNZ2BQ4WWFEIE3USCIHMXQDAMA";
pub const SOUTHGATE: &str = "GDXECRT4O2J7DXOV2WIFBZW33CBZ3R525KVMSURFVZ43VB6TFHKJXMUT";
pub const NORTHWIND: &str = "GCT6FW7OEYYNMVPYJ7JET4Z7RT7TLQ25YRNASKFLLC2EGTRL3W5F3WCE";
pub const AGENT_PK: &str = "94b25ebecb366e10ab91cb54b2f0d1aa17d0b00e537362624a09eacadc792bab";
pub const COSIGNER_PK: &str = "f323b791d74f0cce4fcba65b8a752d79cb7b00b1c0d271b5c38a78b370daaf12";
pub const CLEAN_PAYLOAD: &str = "a0875156e1dc5265cd519cb50ff60e94364fdbb44921a8dbffc97cafa840182f";
pub const CLEAN_AMOUNT: i128 = 80000;
pub const CLEAN_AGENT_SIG: &str = "383daa2bd2bb624397f15d9c138e309fee047d64b565215a575920f9858610d5ce18fe732c5a5a22eae075fec3fb161bf522f22f3e476d15c273d804b5503a08";
pub const CLEAN_COSIGNER_SIG: &str = "ccb5d8e47eab1789896a3504a048e2556a7f01832d344140d7575a9d7654a2a27d526491cfef1177b090d7b52cbcbc9600850e3ef4f7923527b3f721bb079c08";
pub const STEERED_PAYLOAD: &str = "8e620eb9f746ef3a59a3fa366037b95d5977f433f3b41a857def960b6bd5ec32";
pub const STEERED_AMOUNT: i128 = 250000;
pub const STEERED_AGENT_SIG: &str = "c9e24fe5f2aa891a742e16bc3ed3548e5ddae4b236fddd8cd1e109f0a08b44a189279aa4e4ba35a074fc8078d1a59927ab9642af889ff94a99df9e048d46850d";
// Co-signer verdict for the steered payment: escalate (recipient depends on tool:news.example; amount depends on tool:news.example).
