/**
 * Runs the hosted provenance co-signer for the demo site (see hosted.ts).
 *
 * Env: COSIGNER_SECRET (S…, generated by the installer), COSIGNER_PORT (8788),
 *      ALLOWED_ORIGINS (comma-separated site origins), COSIGNER_STATE (file
 *      that keeps registrations; optional).
 * Addresses come from deployments/testnet.json. Bundled into one file with
 * `npm run cosigner:bundle` so the server needs only Node.
 */
import {
  Account,
  BASE_FEE,
  Keypair,
  Operation,
  TransactionBuilder,
  nativeToScVal,
  rpc,
  scValToNative,
  xdr,
} from "@stellar/stellar-sdk";
import { ASSETS, OZ_SMART_ACCOUNT, TESTNET } from "@acan/core";
import deployment from "../../../deployments/testnet.json" with { type: "json" };
import { pinnedCatalog } from "../../site/src/provenance-agent";
import { MERCHANTS } from "../../site/src/merchants";
import { createHostedCosigner, type ChainRule } from "./hosted.js";

if (process.argv.includes("--new-secret")) {
  console.log(Keypair.random().secret());
  process.exit(0);
}
const secret = process.env.COSIGNER_SECRET;
if (!secret) throw new Error("COSIGNER_SECRET is required");
const gatePolicy = (deployment as { cosignerGatePolicy?: string }).cosignerGatePolicy;
if (!gatePolicy) throw new Error("deployments/testnet.json has no cosignerGatePolicy");

const server = new rpc.Server(TESTNET.rpcUrl);
const READER = Keypair.random().publicKey();
async function read(contractId: string, fn: string, args: xdr.ScVal[]): Promise<any> {
  const tx = new TransactionBuilder(new Account(READER, "0"), { fee: BASE_FEE, networkPassphrase: TESTNET.networkPassphrase })
    .addOperation(Operation.invokeContractFunction({ contract: contractId, function: fn, args }))
    .setTimeout(30)
    .build();
  const sim = await server.simulateTransaction(tx);
  if (rpc.Api.isSimulationError(sim)) throw new Error(sim.error);
  return scValToNative((sim as rpc.Api.SimulateTransactionSuccessResponse).result!.retval);
}
const u32 = (n: number) => nativeToScVal(n, { type: "u32" });
const addr = (a: string) => nativeToScVal(a, { type: "address" });

async function readRule(account: string, ruleId: number): Promise<ChainRule> {
  const r = await read(account, "get_context_rule", [u32(ruleId)]);
  const signers = ((r.signers ?? []) as unknown[])
    .filter((s): s is [string, string, Uint8Array] => Array.isArray(s) && s[0] === "External")
    .map((s) => ({ verifier: String(s[1]), key: Buffer.from(s[2]).toString("hex") }));
  return { signers, policies: ((r.policies ?? []) as unknown[]).map(String) };
}

async function readRecipients(policy: string, account: string, ruleId: number): Promise<string[]> {
  return ((await read(policy, "get_recipients", [u32(ruleId), addr(account)])) as unknown[]).map(String);
}

const port = Number(process.env.COSIGNER_PORT ?? 8788);
const svc = createHostedCosigner({
  secret,
  token: ASSETS.xlm.sac,
  networkPassphrase: TESTNET.networkPassphrase,
  ed25519Verifier: OZ_SMART_ACCOUNT.ed25519Verifier,
  gatePolicy,
  merchantPolicy: (deployment as { merchantPolicy?: { address: string } }).merchantPolicy?.address,
  readRule,
  readRecipients,
  catalogFor: (allowed) => pinnedCatalog(allowed ?? MERCHANTS.map((m) => m.address)),
  allowedOrigins: (process.env.ALLOWED_ORIGINS ?? "").split(",").map((s) => s.trim()).filter(Boolean),
  statePath: process.env.COSIGNER_STATE || undefined,
});
svc.listen(port, process.env.HOST ?? "127.0.0.1", () => console.log(`hosted provenance co-signer ${svc.publicKey} on port ${port}`));
